# Reference: https://github.com/marketplace/actions/setup-node-js-environment 
name: Hardhat Build
on:
  push:
    branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup NodeJS 20.11.0
              uses: actions/setup-node@v2
              with:
                node-version: 20.11.0
                cache: npm
            - name: Show NodeJS version 
              run: npm --version
            
            - name: Install Hardhat
              run: npm install --save-dev hardhat@2.22.3
            
            - name: Install Hardhat Dependencies
              run: npm ci
            
            - name: Run Hardhat Test
              run: npx hardhat test